// List of unique enemies for the game

import { ELEMENTS } from './common.js';

export const ENEMY_RARITY = {
  NORMAL: {
    type: 'NORMAL',
    itemDropChance: 1,
    color: 'gray',
    threshold: 80,
    lifeBonus: 1,
    damageBonus: 1,
    bonusAttackSpeed: 1,
    xpBonus: 1,
    goldBonus: 1,
  },
  RARE: {
    type: 'RARE',
    itemDropChance: 1,
    color: 'blue',
    threshold: 90,
    lifeBonus: 1.2,
    damageBonus: 1.2,
    bonusAttackSpeed: 0.9,
    xpBonus: 1.1,
    goldBonus: 1.05,
  },
  EPIC: {
    type: 'EPIC',
    itemDropChance: 2,
    color: 'purple',
    threshold: 96,
    lifeBonus: 1.5,
    damageBonus: 1.5,
    bonusAttackSpeed: 0.8,
    xpBonus: 1.25,
    goldBonus: 1.1,
  },
  LEGENDARY: {
    type: 'LEGENDARY',
    itemDropChance: 2,
    color: 'orange',
    threshold: 99.5,
    lifeBonus: 2,
    damageBonus: 2,
    bonusAttackSpeed: 0.7,
    xpBonus: 1.5,
    goldBonus: 1.2,
  },
  MYTHIC: {
    type: 'MYTHIC',
    itemDropChance: 3,
    color: 'red',
    threshold: 100,
    lifeBonus: 3,
    damageBonus: 3,
    bonusAttackSpeed: 0.5,
    xpBonus: 2,
    goldBonus: 1.5,
  },
};

export const ELEMENT_OPPOSITES = {
  [ELEMENTS.fire.id]: ELEMENTS.air.id,
  [ELEMENTS.earth.id]: ELEMENTS.cold.id,
  [ELEMENTS.cold.id]: ELEMENTS.fire.id,
  [ELEMENTS.air.id]: ELEMENTS.earth.id,
};

export const ENEMY_LIST = [
  {
    name: 'Abyssal Wraith',
    element: 'cold',
    image: 'enemies/abyssal-wraith.jpg',
    lifeMultiplier: 1.2,
    damageMultiplier: 1.1,
    xpMultiplier: 1.0,
    goldMultiplier: 1.0,
    itemDropMultiplier: 1.0,
    materialDropMultiplier: 1.0,
    materialDropWeights: {},
    tags: ['abyss', 'dark'],
    icon: ELEMENTS.cold.icon,
  },
  {
    name: 'Boglurker',
    element: 'earth',
    image: 'enemies/boglurker.jpg',
    lifeMultiplier: 1.1,
    damageMultiplier: 1.0,
    xpMultiplier: 1.0,
    goldMultiplier: 1.0,
    itemDropMultiplier: 1.0,
    materialDropMultiplier: 1.0,
    materialDropWeights: {},
    tags: ['swamp', 'poison'],
    icon: ELEMENTS.earth.icon,
  },
  {
    name: 'Cloudstrider',
    element: 'air',
    image: 'enemies/cloudstrider.jpg',
    lifeMultiplier: 1.0,
    damageMultiplier: 1.2,
    xpMultiplier: 1.0,
    goldMultiplier: 1.0,
    itemDropMultiplier: 1.0,
    materialDropMultiplier: 1.0,
    materialDropWeights: {},
    tags: ['skyrealm', 'air'],
    icon: ELEMENTS.air.icon,
  },
  {
    name: 'Crystal Golem',
    element: 'earth',
    image: 'enemies/crystal-golem.jpg',
    lifeMultiplier: 1.4,
    damageMultiplier: 0.9,
    xpMultiplier: 1.0,
    goldMultiplier: 1.0,
    itemDropMultiplier: 1.0,
    materialDropMultiplier: 1.0,
    materialDropWeights: {
      crystalized_rock: 4,
    },
    tags: ['golem', 'crystal'],
    icon: ELEMENTS.earth.icon,
  },
  {
    name: 'Dreadfang',
    element: 'air',
    image: 'enemies/dreadfang.jpg',
    lifeMultiplier: 1.0,
    damageMultiplier: 1.3,
    xpMultiplier: 1.0,
    goldMultiplier: 1.0,
    itemDropMultiplier: 1.0,
    materialDropMultiplier: 1.0,
    materialDropWeights: {},
    tags: ['nightmare', 'beast'],
    icon: ELEMENTS.air.icon,
  },
  {
    name: 'Dunewraith',
    element: 'earth',
    image: 'enemies/dunewraith.jpg',
    lifeMultiplier: 1.1,
    damageMultiplier: 1.1,
    xpMultiplier: 1.0,
    goldMultiplier: 1.0,
    itemDropMultiplier: 1.0,
    materialDropMultiplier: 1.0,
    materialDropWeights: {},
    tags: ['undead', 'sand'],
    icon: ELEMENTS.earth.icon,
  },
  {
    name: 'Frostbite',
    element: 'cold',
    image: 'enemies/frostbite.jpg',
    lifeMultiplier: 1.0,
    damageMultiplier: 1.2,
    xpMultiplier: 1.0,
    goldMultiplier: 1.0,
    itemDropMultiplier: 1.0,
    materialDropMultiplier: 1.0,
    materialDropWeights: {},
    tags: ['ice', 'cold'],
    icon: ELEMENTS.cold.icon,
  },
  {
    name: 'Frostfury',
    element: 'cold',
    image: 'enemies/frostfury.jpg',
    lifeMultiplier: 1.1,
    damageMultiplier: 1.1,
    xpMultiplier: 1.0,
    goldMultiplier: 1.0,
    itemDropMultiplier: 1.0,
    materialDropMultiplier: 1.0,
    materialDropWeights: {},
    tags: ['ice', 'fury'],
    icon: ELEMENTS.cold.icon,
  },
  {
    name: 'Frostweaver',
    element: 'cold',
    image: 'enemies/frostweaver.jpg',
    lifeMultiplier: 1.2,
    damageMultiplier: 1.0,
    xpMultiplier: 1.0,
    goldMultiplier: 1.0,
    itemDropMultiplier: 1.0,
    materialDropMultiplier: 1.0,
    materialDropWeights: {},
    tags: ['ice', 'spider'],
    icon: ELEMENTS.cold.icon,
  },
  {
    name: 'Gem Guardian',
    element: 'earth',
    image: 'enemies/gem-guardian.jpg',
    lifeMultiplier: 1.3,
    damageMultiplier: 1.0,
    xpMultiplier: 1.0,
    goldMultiplier: 1.0,
    itemDropMultiplier: 1.0,
    materialDropMultiplier: 1.0,
    materialDropWeights: {},
    tags: ['guardian', 'gem'],
    icon: ELEMENTS.earth.icon,
  },
  {
    name: 'Grimspike',
    element: 'earth',
    image: 'enemies/grimspike.jpg',
    lifeMultiplier: 1.2,
    damageMultiplier: 1.1,
    xpMultiplier: 1.0,
    goldMultiplier: 1.0,
    itemDropMultiplier: 1.0,
    materialDropMultiplier: 1.0,
    materialDropWeights: {},
    tags: ['spike', 'earth'],
    icon: ELEMENTS.earth.icon,
  },
  {
    name: 'Sandstalker',
    element: 'earth',
    image: 'enemies/sandstalker.jpg',
    lifeMultiplier: 1.1,
    damageMultiplier: 1.2,
    xpMultiplier: 1.0,
    goldMultiplier: 1.0,
    itemDropMultiplier: 1.0,
    materialDropMultiplier: 1.0,
    materialDropWeights: {},
    tags: ['sand', 'scorpion'],
    icon: ELEMENTS.earth.icon,
  },
  {
    name: 'Shadowclaw',
    element: 'air',
    image: 'enemies/shadowclaw.jpg',
    lifeMultiplier: 1.0,
    damageMultiplier: 1.3,
    xpMultiplier: 1.0,
    goldMultiplier: 1.0,
    itemDropMultiplier: 1.0,
    materialDropMultiplier: 1.0,
    materialDropWeights: {},
    tags: ['shadow', 'beast'],
    icon: ELEMENTS.air.icon,
  },
  {
    name: 'Shardling',
    element: 'earth',
    image: 'enemies/shardling.jpg',
    lifeMultiplier: 1.1,
    damageMultiplier: 1.1,
    xpMultiplier: 1.0,
    goldMultiplier: 1.0,
    itemDropMultiplier: 1.0,
    materialDropMultiplier: 1.0,
    materialDropWeights: {},
    tags: ['shard', 'earth'],
    icon: ELEMENTS.earth.icon,
  },
  {
    name: 'Stormbringer',
    element: 'air',
    image: 'enemies/stormbringer.jpg',
    lifeMultiplier: 1.0,
    damageMultiplier: 1.3,
    xpMultiplier: 1.0,
    goldMultiplier: 1.0,
    itemDropMultiplier: 1.0,
    materialDropMultiplier: 1.0,
    materialDropWeights: {},
    tags: ['storm', 'air'],
    icon: ELEMENTS.air.icon,
  },
  {
    name: 'Stormsoul',
    element: 'air',
    image: 'enemies/stormsoul.jpg',
    lifeMultiplier: 1.1,
    damageMultiplier: 1.2,
    xpMultiplier: 1.0,
    goldMultiplier: 1.0,
    itemDropMultiplier: 1.0,
    materialDropMultiplier: 1.0,
    materialDropWeights: {},
    tags: ['storm', 'soul'],
    icon: ELEMENTS.air.icon,
  },
  {
    name: 'Thunderwing',
    element: 'air',
    image: 'enemies/thunderwing.jpg',
    lifeMultiplier: 1.0,
    damageMultiplier: 1.3,
    xpMultiplier: 1.0,
    goldMultiplier: 1.0,
    itemDropMultiplier: 1.0,
    materialDropMultiplier: 1.0,
    materialDropWeights: {},
    tags: ['thunder', 'air'],
    icon: ELEMENTS.air.icon,
  },
  {
    name: 'Toxictoad',
    element: 'earth',
    image: 'enemies/toxictoad.jpg',
    lifeMultiplier: 1.2,
    damageMultiplier: 1.0,
    xpMultiplier: 1.0,
    goldMultiplier: 1.0,
    itemDropMultiplier: 1.0,
    materialDropMultiplier: 1.0,
    materialDropWeights: {},
    tags: ['toxic', 'frog'],
    icon: ELEMENTS.earth.icon,
  },
  {
    name: 'Venomspitter',
    element: 'earth',
    image: 'enemies/venomspitter.jpg',
    lifeMultiplier: 1.1,
    damageMultiplier: 1.1,
    xpMultiplier: 1.0,
    goldMultiplier: 1.0,
    itemDropMultiplier: 1.0,
    materialDropMultiplier: 1.0,
    materialDropWeights: {},
    tags: ['venom', 'spider'],
    icon: ELEMENTS.earth.icon,
  },
  {
    name: 'Mossback',
    element: 'earth',
    image: 'enemies/mossback.jpg',
    lifeMultiplier: 1.2,
    damageMultiplier: 1.0,
    xpMultiplier: 1.1,
    goldMultiplier: 1.1,
    itemDropMultiplier: 1.0,
    materialDropMultiplier: 1.0,
    materialDropWeights: {},
    tags: ['forest'],
    icon: ELEMENTS.earth.icon,
  },
  {
    name: 'Thornling',
    element: 'earth',
    image: 'enemies/thornling.jpg',
    lifeMultiplier: 1.0,
    damageMultiplier: 1.2,
    xpMultiplier: 1.0,
    goldMultiplier: 1.2,
    itemDropMultiplier: 1.1,
    materialDropMultiplier: 1.0,
    materialDropWeights: {},
    tags: ['forest'],
    icon: ELEMENTS.earth.icon,
  },
  {
    name: 'Barkhide',
    element: 'earth',
    image: 'enemies/barkhide.jpg',
    lifeMultiplier: 1.3,
    damageMultiplier: 1.0,
    xpMultiplier: 1.0,
    goldMultiplier: 1.0,
    itemDropMultiplier: 1.0,
    materialDropMultiplier: 1.1,
    materialDropWeights: {},
    tags: ['forest'],
    icon: ELEMENTS.earth.icon,
  },
  {
    name: 'Sylvan Wisp',
    element: 'air',
    image: 'enemies/sylvan-wisp.jpg',
    lifeMultiplier: 0.9,
    damageMultiplier: 1.3,
    xpMultiplier: 1.2,
    goldMultiplier: 1.0,
    itemDropMultiplier: 1.2,
    materialDropMultiplier: 1.0,
    materialDropWeights: {},
    tags: ['forest'],
    icon: ELEMENTS.air.icon,
  },
];
