// List of unique enemies for the game

export const ENEMY_RARITY = {
  NORMAL: {
    type: 'NORMAL',
    itemDropChance: 1,
    color: 'gray',
    threshold: 80,
    lifeBonus: 1,
    damageBonus: 1,
    bonusAttackSpeed: 1,
  },
  RARE: {
    type: 'RARE',
    itemDropChance: 1,
    color: 'blue',
    threshold: 90,
    lifeBonus: 1.2,
    damageBonus: 1.2,
    bonusAttackSpeed: 0.9,
  },
  EPIC: {
    type: 'EPIC',
    itemDropChance: 2,
    color: 'purple',
    threshold: 96,
    lifeBonus: 1.5,
    damageBonus: 1.5,
    bonusAttackSpeed: 0.8,
  },
  LEGENDARY: {
    type: 'LEGENDARY',
    itemDropChance: 2,
    color: 'orange',
    threshold: 99.5,
    lifeBonus: 2,
    damageBonus: 2,
    bonusAttackSpeed: 0.7,
  },
  MYTHIC: {
    type: 'MYTHIC',
    itemDropChance: 3,
    color: 'red',
    threshold: 100,
    lifeBonus: 3,
    damageBonus: 3,
    bonusAttackSpeed: 0.5,
  },
};

const ELEMENTS = {
  fire: {
    id: 'fire',
    icon: '🔥',
  },
  cold: {
    id: 'cold',
    icon: '❄️',
  },
  air: {
    id: 'air',
    icon: '☁️',
  },
  earth: {
    id: 'earth',
    icon: '🌍',
  },
};

export const ELEMENT_OPPOSITES = {
  [ELEMENTS.fire.id]: ELEMENTS.air.id,
  [ELEMENTS.earth.id]: ELEMENTS.cold.id,
  [ELEMENTS.cold.id]: ELEMENTS.fire.id,
  [ELEMENTS.air.id]: ELEMENTS.earth.id,
};

export const ENEMY_LIST = [
  {
    name: 'Abyssal Wraith',
    icon: '👻',
    element: 'cold',
    image: 'public/enemies/Abyssal Wraith.jpg',
    lifeBonus: 1.2,
    dmgBonus: 1.1,
  },
  {
    name: 'Boglurker',
    icon: '🐸',
    element: 'earth',
    image: 'public/enemies/Boglurker.jpg',
    lifeBonus: 1.1,
    dmgBonus: 1.0,
  },
  {
    name: 'Cloudstrider',
    icon: '☁️',
    element: 'air',
    image: 'public/enemies/Cloudstrider.jpg',
    lifeBonus: 1.0,
    dmgBonus: 1.2,
  },
  {
    name: 'Crystal Golem',
    icon: '🪨',
    element: 'earth',
    image: 'public/enemies/Crystal Golem.jpg',
    lifeBonus: 1.4,
    dmgBonus: 0.9,
  },
  {
    name: 'Dreadfang',
    icon: '🐺',
    element: 'air',
    image: 'public/enemies/Dreadfang.jpg',
    lifeBonus: 1.0,
    dmgBonus: 1.3,
  },
  {
    name: 'Dunewraith',
    icon: '💀',
    element: 'earth',
    image: 'public/enemies/Dunewraith.jpg',
    lifeBonus: 1.1,
    dmgBonus: 1.1,
  },
  {
    name: 'Frostbite',
    icon: '❄️',
    element: 'cold',
    image: 'public/enemies/Frostbite.jpg',
    lifeBonus: 1.0,
    dmgBonus: 1.2,
  },
  {
    name: 'Frostfury',
    icon: '🧊',
    element: 'cold',
    image: 'public/enemies/Frostfury.jpg',
    lifeBonus: 1.1,
    dmgBonus: 1.1,
  },
  {
    name: 'Frostweaver',
    icon: '🕸️',
    element: 'cold',
    image: 'public/enemies/Frostweaver.jpg',
    lifeBonus: 1.2,
    dmgBonus: 1.0,
  },
  {
    name: 'Gem Guardian',
    icon: '💎',
    element: 'earth',
    image: 'public/enemies/Gem Guardian.jpg',
    lifeBonus: 1.3,
    dmgBonus: 1.0,
  },
  {
    name: 'Grimspike',
    icon: '🦔',
    element: 'earth',
    image: 'public/enemies/Grimspike.jpg',
    lifeBonus: 1.2,
    dmgBonus: 1.1,
  },
  {
    name: 'Sandstalker',
    icon: '🦂',
    element: 'earth',
    image: 'public/enemies/Sandstalker.jpg',
    lifeBonus: 1.1,
    dmgBonus: 1.2,
  },
  {
    name: 'Shadowclaw',
    icon: '🐾',
    element: 'air',
    image: 'public/enemies/Shadowclaw.jpg',
    lifeBonus: 1.0,
    dmgBonus: 1.3,
  },
  {
    name: 'Shardling',
    icon: '🔹',
    element: 'earth',
    image: 'public/enemies/Shardling.jpg',
    lifeBonus: 1.1,
    dmgBonus: 1.1,
  },
  {
    name: 'Stormbringer',
    icon: '⚡',
    element: 'air',
    image: 'public/enemies/Stormbringer.jpg',
    lifeBonus: 1.0,
    dmgBonus: 1.3,
  },
  {
    name: 'Stormsoul',
    icon: '🌩️',
    element: 'air',
    image: 'public/enemies/Stormsoul.jpg',
    lifeBonus: 1.1,
    dmgBonus: 1.2,
  },
  {
    name: 'Thunderwing',
    icon: '🦅',
    element: 'air',
    image: 'public/enemies/Thunderwing.jpg',
    lifeBonus: 1.0,
    dmgBonus: 1.3,
  },
  {
    name: 'Toxictoad',
    icon: '🐸',
    element: 'earth',
    image: 'public/enemies/Toxictoad.jpg',
    lifeBonus: 1.2,
    dmgBonus: 1.0,
  },
  {
    name: 'Venomspitter',
    icon: '🕷️',
    element: 'earth',
    image: 'public/enemies/Venomspitter.jpg',
    lifeBonus: 1.1,
    dmgBonus: 1.1,
  },
];
