// List of unique enemies for the game

import { ELEMENTS } from './common.js';

export const ENEMY_RARITY = {
  NORMAL: {
    type: 'NORMAL',
    itemDropChance: 1,
    color: 'gray',
    threshold: 80,
    lifeBonus: 1,
    damageBonus: 1,
    bonusAttackSpeed: 1,
    xpBonus: 1,
    goldBonus: 1,
  },
  RARE: {
    type: 'RARE',
    itemDropChance: 1,
    color: 'blue',
    threshold: 90,
    lifeBonus: 1.2,
    damageBonus: 1.2,
    bonusAttackSpeed: 0.9,
    xpBonus: 1.2,
    goldBonus: 1.05,
  },
  EPIC: {
    type: 'EPIC',
    itemDropChance: 2,
    color: 'purple',
    threshold: 96,
    lifeBonus: 1.5,
    damageBonus: 1.5,
    bonusAttackSpeed: 0.8,
    xpBonus: 1.5,
    goldBonus: 1.1,
  },
  LEGENDARY: {
    type: 'LEGENDARY',
    itemDropChance: 2,
    color: 'orange',
    threshold: 99.5,
    lifeBonus: 2,
    damageBonus: 2,
    bonusAttackSpeed: 0.7,
    xpBonus: 2.5,
    goldBonus: 1.2,
  },
  MYTHIC: {
    type: 'MYTHIC',
    itemDropChance: 3,
    color: 'red',
    threshold: 100,
    lifeBonus: 3,
    damageBonus: 3,
    bonusAttackSpeed: 0.5,
    xpBonus: 4,
    goldBonus: 1.5,
  },
};

export const ELEMENT_OPPOSITES = {
  [ELEMENTS.fire.id]: ELEMENTS.air.id,
  [ELEMENTS.earth.id]: ELEMENTS.cold.id,
  [ELEMENTS.cold.id]: ELEMENTS.fire.id,
  [ELEMENTS.air.id]: ELEMENTS.earth.id,
};

export const ENEMY_LIST = [
  {
    name: 'Abyssal Wraith',
    element: 'cold',
    image: 'enemies/abyssal-wraith.jpg',
    lifeMultiplier: 1.2,
    damageMultiplier: 1.1,
    xpMultiplier: 1.0,
    goldMultiplier: 1.0,
    itemDropMultiplier: 1.0,
    materialDropMultiplier: 1.0,
    materialDropWeights: {},
    tags: ['abyss', 'dark'],
  },
  {
    name: 'Boglurker',
    element: 'earth',
    image: 'enemies/boglurker.jpg',
    lifeMultiplier: 1.1,
    damageMultiplier: 1.0,
    xpMultiplier: 1.0,
    goldMultiplier: 1.0,
    itemDropMultiplier: 1.0,
    materialDropMultiplier: 1.0,
    materialDropWeights: {},
    tags: ['swamp', 'poison'],
  },
  {
    name: 'Cloudstrider',
    element: 'air',
    image: 'enemies/cloudstrider.jpg',
    lifeMultiplier: 1.0,
    damageMultiplier: 1.2,
    xpMultiplier: 1.0,
    goldMultiplier: 1.0,
    itemDropMultiplier: 1.0,
    materialDropMultiplier: 1.0,
    materialDropWeights: {},
    tags: ['skyrealm', 'air'],
  },
  {
    name: 'Crystal Golem',
    element: 'earth',
    image: 'enemies/crystal-golem.jpg',
    lifeMultiplier: 1.4,
    damageMultiplier: 0.9,
    xpMultiplier: 1.0,
    goldMultiplier: 1.0,
    itemDropMultiplier: 1.0,
    materialDropMultiplier: 1.0,
    materialDropWeights: {
      crystalized_rock: 4,
    },
    tags: ['golem', 'crystal'],
  },
  {
    name: 'Dreadfang',
    element: 'air',
    image: 'enemies/dreadfang.jpg',
    lifeMultiplier: 1.0,
    damageMultiplier: 1.3,
    xpMultiplier: 1.0,
    goldMultiplier: 1.0,
    itemDropMultiplier: 1.0,
    materialDropMultiplier: 1.0,
    materialDropWeights: {},
    tags: ['nightmare', 'beast', 'abyss'],
  },
  {
    name: 'Dunewraith',
    element: 'earth',
    image: 'enemies/dunewraith.jpg',
    lifeMultiplier: 1.1,
    damageMultiplier: 1.1,
    xpMultiplier: 1.0,
    goldMultiplier: 1.0,
    itemDropMultiplier: 1.0,
    materialDropMultiplier: 1.0,
    materialDropWeights: {},
    tags: ['undead', 'sand'],
  },
  {
    name: 'Frostbite',
    element: 'cold',
    image: 'enemies/frostbite.jpg',
    lifeMultiplier: 1.0,
    damageMultiplier: 1.2,
    xpMultiplier: 1.0,
    goldMultiplier: 1.0,
    itemDropMultiplier: 1.0,
    materialDropMultiplier: 1.0,
    materialDropWeights: {},
    tags: ['ice', 'cold'],
  },
  {
    name: 'Frostfury',
    element: 'cold',
    image: 'enemies/frostfury.jpg',
    lifeMultiplier: 1.1,
    damageMultiplier: 1.1,
    xpMultiplier: 1.0,
    goldMultiplier: 1.0,
    itemDropMultiplier: 1.0,
    materialDropMultiplier: 1.0,
    materialDropWeights: {},
    tags: ['ice', 'fury'],
  },
  {
    name: 'Frostweaver',
    element: 'cold',
    image: 'enemies/frostweaver.jpg',
    lifeMultiplier: 1.2,
    damageMultiplier: 1.0,
    xpMultiplier: 1.0,
    goldMultiplier: 1.0,
    itemDropMultiplier: 1.0,
    materialDropMultiplier: 1.0,
    materialDropWeights: {},
    tags: ['ice', 'spider'],
  },
  {
    name: 'Gem Guardian',
    element: 'earth',
    image: 'enemies/gem-guardian.jpg',
    lifeMultiplier: 1.3,
    damageMultiplier: 1.0,
    xpMultiplier: 1.0,
    goldMultiplier: 1.0,
    itemDropMultiplier: 1.0,
    materialDropMultiplier: 1.0,
    materialDropWeights: {},
    tags: ['guardian', 'gem', 'cave'],
  },
  {
    name: 'Grimspike',
    element: 'earth',
    image: 'enemies/grimspike.jpg',
    lifeMultiplier: 1.2,
    damageMultiplier: 1.1,
    xpMultiplier: 1.0,
    goldMultiplier: 1.0,
    itemDropMultiplier: 1.0,
    materialDropMultiplier: 1.0,
    materialDropWeights: {},
    tags: ['spike', 'earth', 'cave'],
  },
  {
    name: 'Sandstalker',
    element: 'earth',
    image: 'enemies/sandstalker.jpg',
    lifeMultiplier: 1.1,
    damageMultiplier: 1.2,
    xpMultiplier: 1.0,
    goldMultiplier: 1.0,
    itemDropMultiplier: 1.0,
    materialDropMultiplier: 1.0,
    materialDropWeights: {},
    tags: ['sand', 'scorpion'],
  },
  {
    name: 'Shadowclaw',
    element: 'air',
    image: 'enemies/shadowclaw.jpg',
    lifeMultiplier: 1.0,
    damageMultiplier: 1.3,
    xpMultiplier: 1.0,
    goldMultiplier: 1.0,
    itemDropMultiplier: 1.0,
    materialDropMultiplier: 1.0,
    materialDropWeights: {},
    tags: ['shadow', 'beast', 'abyss'],
  },
  {
    name: 'Shardling',
    element: 'earth',
    image: 'enemies/shardling.jpg',
    lifeMultiplier: 1.1,
    damageMultiplier: 1.1,
    xpMultiplier: 1.0,
    goldMultiplier: 1.0,
    itemDropMultiplier: 1.0,
    materialDropMultiplier: 1.0,
    materialDropWeights: {},
    tags: ['shard', 'earth', 'cave'],
  },
  {
    name: 'Stormbringer',
    element: 'air',
    image: 'enemies/stormbringer.jpg',
    lifeMultiplier: 1.0,
    damageMultiplier: 1.3,
    xpMultiplier: 1.0,
    goldMultiplier: 1.0,
    itemDropMultiplier: 1.0,
    materialDropMultiplier: 1.0,
    materialDropWeights: {},
    tags: ['storm', 'air'],
  },
  {
    name: 'Stormsoul',
    element: 'air',
    image: 'enemies/stormsoul.jpg',
    lifeMultiplier: 1.1,
    damageMultiplier: 1.2,
    xpMultiplier: 1.0,
    goldMultiplier: 1.0,
    itemDropMultiplier: 1.0,
    materialDropMultiplier: 1.0,
    materialDropWeights: {},
    tags: ['storm', 'soul', 'sky'],
  },
  {
    name: 'Thunderwing',
    element: 'air',
    image: 'enemies/thunderwing.jpg',
    lifeMultiplier: 1.0,
    damageMultiplier: 1.3,
    xpMultiplier: 1.0,
    goldMultiplier: 1.0,
    itemDropMultiplier: 1.0,
    materialDropMultiplier: 1.0,
    materialDropWeights: {},
    tags: ['thunder', 'air'],
  },
  {
    name: 'Toxictoad',
    element: 'earth',
    image: 'enemies/toxictoad.jpg',
    lifeMultiplier: 1.2,
    damageMultiplier: 1.0,
    xpMultiplier: 1.0,
    goldMultiplier: 1.0,
    itemDropMultiplier: 1.0,
    materialDropMultiplier: 1.0,
    materialDropWeights: {},
    tags: ['toxic', 'frog', 'swamp'],
  },
  {
    name: 'Venomspitter',
    element: 'earth',
    image: 'enemies/venomspitter.jpg',
    lifeMultiplier: 1.1,
    damageMultiplier: 1.1,
    xpMultiplier: 1.0,
    goldMultiplier: 1.0,
    itemDropMultiplier: 1.0,
    materialDropMultiplier: 1.0,
    materialDropWeights: {},
    tags: ['venom', 'spider', 'swamp'],
  },
  {
    name: 'Mossback',
    element: 'earth',
    image: 'enemies/mossback.jpg',
    lifeMultiplier: 1.2,
    damageMultiplier: 1.0,
    xpMultiplier: 1.1,
    goldMultiplier: 1.1,
    itemDropMultiplier: 1.0,
    materialDropMultiplier: 1.0,
    materialDropWeights: {},
    tags: ['forest'],
  },
  {
    name: 'Thornling',
    element: 'earth',
    image: 'enemies/thornling.jpg',
    lifeMultiplier: 1.0,
    damageMultiplier: 1.2,
    xpMultiplier: 1.0,
    goldMultiplier: 1.2,
    itemDropMultiplier: 1.1,
    materialDropMultiplier: 1.0,
    materialDropWeights: {},
    tags: ['forest'],
  },
  {
    name: 'Barkhide',
    element: 'earth',
    image: 'enemies/barkhide.jpg',
    lifeMultiplier: 1.3,
    damageMultiplier: 1.0,
    xpMultiplier: 1.0,
    goldMultiplier: 1.0,
    itemDropMultiplier: 1.0,
    materialDropMultiplier: 1.1,
    materialDropWeights: {},
    tags: ['forest'],
  },
  {
    name: 'Sylvan Wisp',
    element: 'air',
    image: 'enemies/sylvan-wisp.jpg',
    lifeMultiplier: 0.9,
    damageMultiplier: 1.3,
    xpMultiplier: 1.2,
    goldMultiplier: 1.0,
    itemDropMultiplier: 1.2,
    materialDropMultiplier: 1.0,
    materialDropWeights: {},
    tags: ['forest'],
  },
  {
    name: 'Magma Titan',
    element: 'fire',
    image: 'enemies/magma-titan.jpg',
    lifeMultiplier: 1.8,
    damageMultiplier: 1.5,
    xpMultiplier: 1.0,
    goldMultiplier: 1.0,
    itemDropMultiplier: 1.0,
    materialDropMultiplier: 1.2,
    materialDropWeights: {},
    tags: ['volcano', 'fire'],
  },
  {
    name: 'Ember Drake',
    element: 'fire',
    image: 'enemies/ember-drake.jpg',
    lifeMultiplier: 1.3,
    damageMultiplier: 1.4,
    xpMultiplier: 1.1,
    goldMultiplier: 1.0,
    itemDropMultiplier: 1.0,
    materialDropMultiplier: 1.0,
    materialDropWeights: {},
    tags: ['volcano', 'fire'],
  },
  {
    name: 'Lava Elemental',
    element: 'fire',
    image: 'enemies/lava-elemental.jpg',
    lifeMultiplier: 1.4,
    damageMultiplier: 1.2,
    xpMultiplier: 1.0,
    goldMultiplier: 1.1,
    itemDropMultiplier: 1.0,
    materialDropMultiplier: 1.1,
    materialDropWeights: {},
    tags: ['volcano', 'fire'],
  },
  {
    name: 'Tide Guardian',
    element: 'cold',
    image: 'enemies/tide-guardian.jpg',
    lifeMultiplier: 1.5,
    damageMultiplier: 1.1,
    xpMultiplier: 1.0,
    goldMultiplier: 1.0,
    itemDropMultiplier: 1.0,
    materialDropMultiplier: 1.2,
    materialDropWeights: {},
    tags: ['ruins', 'water'],
  },
  {
    name: 'Coral Sentinel',
    element: 'earth',
    image: 'enemies/coral-sentinel.jpg',
    lifeMultiplier: 1.6,
    damageMultiplier: 1.0,
    xpMultiplier: 1.1,
    goldMultiplier: 1.0,
    itemDropMultiplier: 1.0,
    materialDropMultiplier: 1.0,
    materialDropWeights: {},
    tags: ['ruins', 'water'],
  },
  {
    name: 'Depths Leviathan',
    element: 'cold',
    image: 'enemies/depths-leviathan.jpg',
    lifeMultiplier: 1.7,
    damageMultiplier: 1.3,
    xpMultiplier: 1.2,
    goldMultiplier: 1.0,
    itemDropMultiplier: 1.1,
    materialDropMultiplier: 1.0,
    materialDropWeights: {},
    tags: ['ruins', 'water'],
  },
  {
    name: 'Banshee',
    element: 'air',
    image: 'enemies/banshee.jpg',
    lifeMultiplier: 1.0,
    damageMultiplier: 1.4,
    xpMultiplier: 1.3,
    goldMultiplier: 1.0,
    itemDropMultiplier: 1.0,
    materialDropMultiplier: 1.0,
    materialDropWeights: {},
    tags: ['haunted', 'spirit'],
  },
  {
    name: 'Phantom',
    element: 'cold',
    image: 'enemies/phantom.jpg',
    lifeMultiplier: 1.1,
    damageMultiplier: 1.3,
    xpMultiplier: 1.1,
    goldMultiplier: 1.0,
    itemDropMultiplier: 1.0,
    materialDropMultiplier: 1.0,
    materialDropWeights: {},
    tags: ['haunted', 'spirit'],
  },
  {
    name: 'Wraith Lord',
    element: 'earth',
    image: 'enemies/wraith-lord.jpg',
    lifeMultiplier: 1.6,
    damageMultiplier: 1.2,
    xpMultiplier: 1.2,
    goldMultiplier: 1.1,
    itemDropMultiplier: 1.0,
    materialDropMultiplier: 1.0,
    materialDropWeights: {},
    tags: ['haunted', 'spirit'],
  },
  {
    name: 'Golden Sphinx',
    element: 'earth',
    image: 'enemies/golden-sphinx.jpg',
    lifeMultiplier: 1.4,
    damageMultiplier: 1.2,
    xpMultiplier: 1.0,
    goldMultiplier: 1.8,
    itemDropMultiplier: 1.0,
    materialDropMultiplier: 1.0,
    materialDropWeights: {},
    tags: ['steppe', 'gold'],
  },
  {
    name: 'Aurelius',
    element: 'fire',
    image: 'enemies/aurelius.jpg',
    lifeMultiplier: 1.2,
    damageMultiplier: 1.3,
    xpMultiplier: 1.1,
    goldMultiplier: 1.5,
    itemDropMultiplier: 1.0,
    materialDropMultiplier: 1.0,
    materialDropWeights: {},
    tags: ['steppe', 'gold'],
  },
  {
    name: 'Midas Beast',
    element: 'air',
    image: 'enemies/midas-beast.jpg',
    lifeMultiplier: 1.3,
    damageMultiplier: 1.1,
    xpMultiplier: 1.0,
    goldMultiplier: 2.0,
    itemDropMultiplier: 1.0,
    materialDropMultiplier: 1.0,
    materialDropWeights: {},
    tags: ['steppe', 'gold'],
  },
  {
    name: 'Void Sentinel',
    element: 'cold',
    image: 'enemies/void-sentinel.jpg',
    lifeMultiplier: 1.8,
    damageMultiplier: 1.4,
    xpMultiplier: 1.3,
    goldMultiplier: 1.0,
    itemDropMultiplier: 1.1,
    materialDropMultiplier: 1.2,
    materialDropWeights: {},
    tags: ['obsidian', 'arcane'],
  },
  {
    name: 'Arcane Construct',
    element: 'air',
    image: 'enemies/arcane-construct.jpg',
    lifeMultiplier: 1.5,
    damageMultiplier: 1.5,
    xpMultiplier: 1.1,
    goldMultiplier: 1.0,
    itemDropMultiplier: 1.0,
    materialDropMultiplier: 1.3,
    materialDropWeights: {},
    tags: ['obsidian', 'arcane'],
  },
  {
    name: 'Obsidian Golem',
    element: 'earth',
    image: 'enemies/obsidian-golem.jpg',
    lifeMultiplier: 2.0,
    damageMultiplier: 1.2,
    xpMultiplier: 1.2,
    goldMultiplier: 1.0,
    itemDropMultiplier: 1.0,
    materialDropMultiplier: 1.4,
    materialDropWeights: {},
    tags: ['obsidian', 'arcane'],
  },
  {
    name: 'Frost Giant',
    element: 'cold',
    image: 'enemies/frost-giant.jpg',
    lifeMultiplier: 1.8,
    damageMultiplier: 1.3,
    xpMultiplier: 1.1,
    goldMultiplier: 1.0,
    itemDropMultiplier: 1.0,
    materialDropMultiplier: 1.1,
    materialDropWeights: {},
    tags: ['tundra', 'ice'],
  },
  {
    name: 'Ice Wraith',
    element: 'cold',
    image: 'enemies/ice-wraith.jpg',
    lifeMultiplier: 1.2,
    damageMultiplier: 1.4,
    xpMultiplier: 1.0,
    goldMultiplier: 1.0,
    itemDropMultiplier: 1.0,
    materialDropMultiplier: 1.0,
    materialDropWeights: {},
    tags: ['tundra', 'ice'],
  },
  {
    name: 'Wildfire Spirit',
    element: 'fire',
    image: 'enemies/wildfire-spirit.jpg',
    lifeMultiplier: 1.0,
    damageMultiplier: 1.3,
    xpMultiplier: 1.1,
    goldMultiplier: 1.0,
    itemDropMultiplier: 1.0,
    materialDropMultiplier: 1.0,
    materialDropWeights: {},
    tags: ['forest', 'fire'],
    icon: ELEMENTS.fire.icon,
  },
  {
    name: 'Scorching Salamander',
    element: 'fire',
    image: 'enemies/scorching-salamander.jpg',
    lifeMultiplier: 1.2,
    damageMultiplier: 1.2,
    xpMultiplier: 1.0,
    goldMultiplier: 1.0,
    itemDropMultiplier: 1.0,
    materialDropMultiplier: 1.0,
    materialDropWeights: {},
    tags: ['desert', 'fire'],
    icon: ELEMENTS.fire.icon,
  },
  {
    name: 'Dune Blazer',
    element: 'fire',
    image: 'enemies/dune-blazer.jpg',
    lifeMultiplier: 1.1,
    damageMultiplier: 1.4,
    xpMultiplier: 1.0,
    goldMultiplier: 1.2,
    itemDropMultiplier: 1.0,
    materialDropMultiplier: 1.0,
    materialDropWeights: {},
    tags: ['desert', 'sand'],
    icon: ELEMENTS.fire.icon,
  },
  {
    name: 'Hellhound',
    element: 'fire',
    image: 'enemies/hellhound.jpg',
    lifeMultiplier: 1.3,
    damageMultiplier: 1.3,
    xpMultiplier: 1.2,
    goldMultiplier: 1.0,
    itemDropMultiplier: 1.0,
    materialDropMultiplier: 1.0,
    materialDropWeights: {},
    tags: ['abyss', 'dark'],
    icon: ELEMENTS.fire.icon,
  },
  {
    name: 'Infernal Knight',
    element: 'fire',
    image: 'enemies/infernal-knight.jpg',
    lifeMultiplier: 1.6,
    damageMultiplier: 1.2,
    xpMultiplier: 1.1,
    goldMultiplier: 1.0,
    itemDropMultiplier: 1.0,
    materialDropMultiplier: 1.1,
    materialDropWeights: {},
    tags: ['abyss', 'dark'],
    icon: ELEMENTS.fire.icon,
  },
  {
    name: 'Molten Wyrm',
    element: 'fire',
    image: 'enemies/molten-wyrm.jpg',
    lifeMultiplier: 1.7,
    damageMultiplier: 1.4,
    xpMultiplier: 1.0,
    goldMultiplier: 1.0,
    itemDropMultiplier: 1.0,
    materialDropMultiplier: 1.3,
    materialDropWeights: {},
    tags: ['volcano', 'fire'],
    icon: ELEMENTS.fire.icon,
  },
  {
    name: 'Solar Phoenix',
    element: 'fire',
    image: 'enemies/solar-phoenix.jpg',
    lifeMultiplier: 1.4,
    damageMultiplier: 1.5,
    xpMultiplier: 1.3,
    goldMultiplier: 1.3,
    itemDropMultiplier: 1.1,
    materialDropMultiplier: 1.0,
    materialDropWeights: {},
    tags: ['steppe', 'gold'],
    icon: ELEMENTS.fire.icon,
  },
  {
    name: 'Radiant Lion',
    element: 'fire',
    image: 'enemies/radiant-lion.jpg',
    lifeMultiplier: 1.5,
    damageMultiplier: 1.3,
    xpMultiplier: 1.1,
    goldMultiplier: 1.6,
    itemDropMultiplier: 1.0,
    materialDropMultiplier: 1.0,
    materialDropWeights: {},
    tags: ['steppe', 'gold'],
    icon: ELEMENTS.fire.icon,
  },
  {
    name: 'Crimson Wisp',
    element: 'fire',
    image: 'enemies/crimson-wisp.jpg',
    lifeMultiplier: 0.8,
    damageMultiplier: 1.6,
    xpMultiplier: 1.2,
    goldMultiplier: 1.0,
    itemDropMultiplier: 1.2,
    materialDropMultiplier: 1.0,
    materialDropWeights: {},
    tags: ['obsidian', 'arcane'],
    icon: ELEMENTS.fire.icon,
  },
  {
    name: 'Flame Djinn',
    element: 'fire',
    image: 'enemies/flame-djinn.jpg',
    lifeMultiplier: 1.8,
    damageMultiplier: 1.4,
    xpMultiplier: 1.4,
    goldMultiplier: 1.0,
    itemDropMultiplier: 1.0,
    materialDropMultiplier: 1.5,
    materialDropWeights: {},
    tags: ['obsidian', 'arcane'],
    icon: ELEMENTS.fire.icon,
  },
];
