// Define quest definitions
export const QUEST_DEFINITIONS = [
  // Kill quests
  {
    id: 'kill10',
    category: 'kills',
    title: 'First Blood',
    description: 'Defeat 10 enemies.',
    type: 'kill',
    target: 10,
    reward: { gold: 100, crystals: 1 },
    icon: '⚔️',
  },
  {
    id: 'kill100',
    category: 'kills',
    title: 'Rampage',
    description: 'Defeat 100 enemies.',
    type: 'kill',
    target: 100,
    reward: { gold: 500, crystals: 3 },
    icon: '💥',
  },
  {
    id: 'kill1000',
    category: 'kills',
    title: 'Massacre',
    description: 'Defeat 1000 enemies.',
    type: 'kill',
    target: 1000,
    reward: { gold: 5000, crystals: 5 },
    icon: '💥',
  },
  // Rarity kill quests
  {
    id: 'kill_rare_10',
    category: 'rarity',
    title: 'Rare Hunter',
    description: 'Defeat 10 rare enemies.',
    type: 'kill_rarity',
    rarity: 'rare',
    target: 10,
    reward: { gold: 300, crystals: 2 },
    icon: '🔵',
  },
  {
    id: 'kill_epic_5',
    category: 'rarity',
    title: 'Epic Slayer',
    description: 'Defeat 5 epic enemies.',
    type: 'kill_rarity',
    rarity: 'epic',
    target: 5,
    reward: { gold: 1000, crystals: 3 },
    icon: '🟣',
  },
  {
    id: 'kill_legendary_1',
    category: 'rarity',
    title: 'Legendary Conqueror',
    description: 'Defeat 1 legendary enemy.',
    type: 'kill_rarity',
    rarity: 'legendary',
    target: 1,
    reward: { gold: 2500, crystals: 5 },
    icon: '🟠',
  },
  {
    id: 'kill_mythic_1',
    category: 'rarity',
    title: 'Mythic Bane',
    description: 'Defeat 1 mythic enemy.',
    type: 'kill_rarity',
    rarity: 'mythic',
    target: 1,
    reward: { gold: 5000, crystals: 10 },
    icon: '🔴',
  },
  // Resource quests
  {
    id: 'gold_10000',
    category: 'resources',
    title: 'Gold Hoarder',
    description: 'Earn a total of 10,000 gold.',
    type: 'resource',
    resource: 'totalGoldEarned',
    target: 10000,
    reward: { crystals: 2 },
    icon: '💰',
  },
  {
    id: 'gold_100000',
    category: 'resources',
    title: 'Treasure Tycoon',
    description: 'Earn a total of 100,000 gold.',
    type: 'resource',
    resource: 'totalGoldEarned',
    target: 100000,
    reward: { crystals: 5 },
    icon: '🏆',
  },
  {
    id: 'crystals_10',
    category: 'resources',
    title: 'Crystal Collector',
    description: 'Earn a total of 10 crystals.',
    type: 'resource',
    resource: 'crystals',
    target: 10,
    reward: { gold: 2000 },
    icon: '🔷',
  },
  // Progression quests
  {
    id: 'level_10',
    category: 'progression',
    title: 'Novice Adventurer',
    description: 'Reach level 10.',
    type: 'level',
    target: 10,
    reward: { gold: 500 },
    icon: '🧙',
  },
  {
    id: 'level_50',
    category: 'progression',
    title: 'Seasoned Hero',
    description: 'Reach level 50.',
    type: 'level',
    target: 50,
    reward: { gold: 2000, crystals: 2 },
    icon: '🦸',
  },
  {
    id: 'stage_50',
    category: 'progression',
    title: 'Explorer',
    description: 'Reach stage 50.',
    type: 'stage',
    target: 50,
    reward: { gold: 1000 },
    icon: '🗺️',
  },
  {
    id: 'damage_1000',
    category: 'progression',
    title: 'Big Hit',
    description: 'Deal 1,000 damage in a single hit.',
    type: 'damage',
    target: 1000,
    reward: { crystals: 1 },
    icon: '💥',
  },
];
