// Define quest definitions
export const QUEST_DEFINITIONS = [
  // Kill quests
  {
    id: 'kill10',
    category: 'kills',
    title: 'First Blood',
    description: 'Defeat 10 enemies.',
    type: 'kill',
    target: 10,
    reward: { gold: 500 },
    icon: '⚔️',
  },
  {
    id: 'kill50',
    category: 'kills',
    title: 'Warrior',
    description: 'Defeat 50 enemies.',
    type: 'kill',
    target: 50,
    reward: { gold: 1500 },
    icon: '⚔️',
  },
  {
    id: 'kill250',
    category: 'kills',
    title: 'Destroyer',
    description: 'Defeat 250 enemies.',
    type: 'kill',
    target: 250,
    reward: { gold: 4000 },
    icon: '💥',
  },
  {
    id: 'kill1000',
    category: 'kills',
    title: 'Massacre',
    description: 'Defeat 1000 enemies.',
    type: 'kill',
    target: 1000,
    reward: { gold: 10000, crystals: 1 },
    icon: '💀',
  },
  {
    id: 'kill2500',
    category: 'kills',
    title: 'Harbinger',
    description: 'Defeat 2500 enemies.',
    type: 'kill',
    target: 2500,
    reward: { gold: 30000, crystals: 4 },
    icon: '💀',
  },
  {
    id: 'kill5000',
    category: 'kills',
    title: 'Death Incarnate',
    description: 'Defeat 5000 enemies.',
    type: 'kill',
    target: 5000,
    reward: { gold: 60000, crystals: 2 },
    icon: '☠️',
  },
  {
    id: 'kill10000',
    category: 'kills',
    title: 'Apocalypse',
    description: 'Defeat 10000 enemies.',
    type: 'kill',
    target: 10000,
    reward: { gold: 100000, crystals: 3 },
    icon: '☠️',
  },
  {
    id: 'kill25000',
    category: 'kills',
    title: 'World Ender',
    description: 'Defeat 25000 enemies.',
    type: 'kill',
    target: 25000,
    reward: { gold: 200000, crystals: 5 },
    icon: '🌍',
  },
  {
    id: 'kill50000',
    category: 'kills',
    title: 'Extinction Event',
    description: 'Defeat 50000 enemies.',
    type: 'kill',
    target: 50000,
    reward: { gold: 400000, crystals: 8 },
    icon: '🌍',
  },
  {
    id: 'kill100000',
    category: 'kills',
    title: 'Universal Threat',
    description: 'Defeat 100000 enemies.',
    type: 'kill',
    target: 100000,
    reward: { gold: 700000, crystals: 12 },
    icon: '🌌',
  },
  {
    id: 'kill250000',
    category: 'kills',
    title: 'Cosmic Terror',
    description: 'Defeat 250000 enemies.',
    type: 'kill',
    target: 250000,
    reward: { gold: 2000000, crystals: 20 },
    icon: '🌌',
  },
  {
    id: 'kill500000',
    category: 'kills',
    title: 'Reality Breaker',
    description: 'Defeat 500000 enemies.',
    type: 'kill',
    target: 500000,
    reward: { gold: 6000000, crystals: 30 },
    icon: '⭐',
  },
  {
    id: 'kill1000000',
    category: 'kills',
    title: 'Infinite Void',
    description: 'Defeat 1000000 enemies.',
    type: 'kill',
    target: 1000000,
    reward: { gold: 15000000, crystals: 50 },
    icon: '⭐',
  }, // Rarity kill quests
  {
    id: 'kill_rare_10',
    category: 'rarity',
    title: 'Rare Hunter',
    description: 'Defeat 10 rare enemies.',
    type: 'kill_rarity',
    rarity: 'rare',
    target: 10,
    reward: { gold: 300, crystals: 1 },
    icon: '🔵',
  },
  {
    id: 'kill_rare_50',
    category: 'rarity',
    title: 'Rare Specialist',
    description: 'Defeat 50 rare enemies.',
    type: 'kill_rarity',
    rarity: 'rare',
    target: 50,
    reward: { gold: 1500, crystals: 1 },
    icon: '🔵',
  },
  {
    id: 'kill_rare_100',
    category: 'rarity',
    title: 'Rare Exterminator',
    description: 'Defeat 100 rare enemies.',
    type: 'kill_rarity',
    rarity: 'rare',
    target: 100,
    reward: { gold: 3000, crystals: 2 },
    icon: '🔵',
  },
  {
    id: 'kill_rare_500',
    category: 'rarity',
    title: 'Rare Nemesis',
    description: 'Defeat 500 rare enemies.',
    type: 'kill_rarity',
    rarity: 'rare',
    target: 500,
    reward: { gold: 15000, crystals: 3 },
    icon: '🔵',
  },
  {
    id: 'kill_rare_1000',
    category: 'rarity',
    title: 'Rare Apocalypse',
    description: 'Defeat 1000 rare enemies.',
    type: 'kill_rarity',
    rarity: 'rare',
    target: 1000,
    reward: { gold: 30000, crystals: 5 },
    icon: '🔵',
  },
  {
    id: 'kill_epic_5',
    category: 'rarity',
    title: 'Epic Slayer',
    description: 'Defeat 5 epic enemies.',
    type: 'kill_rarity',
    rarity: 'epic',
    target: 5,
    reward: { gold: 1000, crystals: 1 },
    icon: '🟣',
  },
  {
    id: 'kill_epic_25',
    category: 'rarity',
    title: 'Epic Destroyer',
    description: 'Defeat 25 epic enemies.',
    type: 'kill_rarity',
    rarity: 'epic',
    target: 25,
    reward: { gold: 5000, crystals: 2 },
    icon: '🟣',
  },
  {
    id: 'kill_epic_50',
    category: 'rarity',
    title: 'Epic Vanquisher',
    description: 'Defeat 50 epic enemies.',
    type: 'kill_rarity',
    rarity: 'epic',
    target: 50,
    reward: { gold: 10000, crystals: 3 },
    icon: '🟣',
  },
  {
    id: 'kill_epic_100',
    category: 'rarity',
    title: 'Epic Bane',
    description: 'Defeat 100 epic enemies.',
    type: 'kill_rarity',
    rarity: 'epic',
    target: 100,
    reward: { gold: 20000, crystals: 5 },
    icon: '🟣',
  },
  {
    id: 'kill_epic_500',
    category: 'rarity',
    title: 'Epic Annihilator',
    description: 'Defeat 500 epic enemies.',
    type: 'kill_rarity',
    rarity: 'epic',
    target: 500,
    reward: { gold: 100000, crystals: 8 },
    icon: '🟣',
  },
  {
    id: 'kill_legendary_1',
    category: 'rarity',
    title: 'Legendary Conqueror',
    description: 'Defeat 1 legendary enemy.',
    type: 'kill_rarity',
    rarity: 'legendary',
    target: 1,
    reward: { gold: 2500, crystals: 2 },
    icon: '🟠',
  },
  {
    id: 'kill_legendary_10',
    category: 'rarity',
    title: 'Legendary Hunter',
    description: 'Defeat 10 legendary enemies.',
    type: 'kill_rarity',
    rarity: 'legendary',
    target: 10,
    reward: { gold: 25000, crystals: 5 },
    icon: '🟠',
  },
  {
    id: 'kill_legendary_25',
    category: 'rarity',
    title: 'Legendary Slayer',
    description: 'Defeat 25 legendary enemies.',
    type: 'kill_rarity',
    rarity: 'legendary',
    target: 25,
    reward: { gold: 62500, crystals: 8 },
    icon: '🟠',
  },
  {
    id: 'kill_legendary_50',
    category: 'rarity',
    title: 'Legendary Destroyer',
    description: 'Defeat 50 legendary enemies.',
    type: 'kill_rarity',
    rarity: 'legendary',
    target: 50,
    reward: { gold: 125000, crystals: 12 },
    icon: '🟠',
  },
  {
    id: 'kill_legendary_100',
    category: 'rarity',
    title: 'Legendary Nightmare',
    description: 'Defeat 100 legendary enemies.',
    type: 'kill_rarity',
    rarity: 'legendary',
    target: 100,
    reward: { gold: 250000, crystals: 20 },
    icon: '🟠',
  },
  {
    id: 'kill_mythic_1',
    category: 'rarity',
    title: 'Mythic Bane',
    description: 'Defeat 1 mythic enemy.',
    type: 'kill_rarity',
    rarity: 'mythic',
    target: 1,
    reward: { gold: 5000, crystals: 3 },
    icon: '🔴',
  },
  {
    id: 'kill_mythic_5',
    category: 'rarity',
    title: 'Mythic Slayer',
    description: 'Defeat 5 mythic enemies.',
    type: 'kill_rarity',
    rarity: 'mythic',
    target: 5,
    reward: { gold: 25000, crystals: 8 },
    icon: '🔴',
  },
  {
    id: 'kill_mythic_10',
    category: 'rarity',
    title: 'Mythic Hunter',
    description: 'Defeat 10 mythic enemies.',
    type: 'kill_rarity',
    rarity: 'mythic',
    target: 10,
    reward: { gold: 50000, crystals: 15 },
    icon: '🔴',
  },
  {
    id: 'kill_mythic_25',
    category: 'rarity',
    title: 'Mythic Destroyer',
    description: 'Defeat 25 mythic enemies.',
    type: 'kill_rarity',
    rarity: 'mythic',
    target: 25,
    reward: { gold: 125000, crystals: 25 },
    icon: '🔴',
  },
  {
    id: 'kill_mythic_50',
    category: 'rarity',
    title: 'Mythic Apocalypse',
    description: 'Defeat 50 mythic enemies.',
    type: 'kill_rarity',
    rarity: 'mythic',
    target: 50,
    reward: { gold: 250000, crystals: 40 },
    icon: '🔴',
  }, // Resource quests
  {
    id: 'gold_1000',
    category: 'resources',
    title: 'Pocket Change',
    description: 'Earn a total of 1,000 gold.',
    type: 'resource',
    resource: 'totalGoldEarned',
    target: 1000,
    reward: { gold: 500 },
    icon: '💰',
  },
  {
    id: 'gold_5000',
    category: 'resources',
    title: 'Small Fortune',
    description: 'Earn a total of 5,000 gold.',
    type: 'resource',
    resource: 'totalGoldEarned',
    target: 5000,
    reward: { crystals: 1 },
    icon: '💰',
  },
  {
    id: 'gold_15000',
    category: 'resources',
    title: 'Gold Hoarder',
    description: 'Earn a total of 15,000 gold.',
    type: 'resource',
    resource: 'totalGoldEarned',
    target: 15000,
    reward: { crystals: 1 },
    icon: '💰',
  },
  {
    id: 'gold_50000',
    category: 'resources',
    title: 'Wealthy Adventurer',
    description: 'Earn a total of 50,000 gold.',
    type: 'resource',
    resource: 'totalGoldEarned',
    target: 50000,
    reward: { crystals: 1 },
    icon: '💰',
  },
  {
    id: 'gold_150000',
    category: 'resources',
    title: 'Rich Merchant',
    description: 'Earn a total of 150,000 gold.',
    type: 'resource',
    resource: 'totalGoldEarned',
    target: 150000,
    reward: { crystals: 2 },
    icon: '💰',
  },
  {
    id: 'gold_500000',
    category: 'resources',
    title: 'Treasure Tycoon',
    description: 'Earn a total of 500,000 gold.',
    type: 'resource',
    resource: 'totalGoldEarned',
    target: 500000,
    reward: { crystals: 2 },
    icon: '🏆',
  },
  {
    id: 'gold_1500000',
    category: 'resources',
    title: 'Gold Baron',
    description: 'Earn a total of 1,500,000 gold.',
    type: 'resource',
    resource: 'totalGoldEarned',
    target: 1500000,
    reward: { crystals: 3 },
    icon: '🏆',
  },
  {
    id: 'gold_5000000',
    category: 'resources',
    title: 'Millionaire',
    description: 'Earn a total of 5,000,000 gold.',
    type: 'resource',
    resource: 'totalGoldEarned',
    target: 5000000,
    reward: { crystals: 5 },
    icon: '🏆',
  },
  {
    id: 'gold_15000000',
    category: 'resources',
    title: 'Golden Emperor',
    description: 'Earn a total of 15,000,000 gold.',
    type: 'resource',
    resource: 'totalGoldEarned',
    target: 15000000,
    reward: { crystals: 8 },
    icon: '👑',
  },
  {
    id: 'gold_50000000',
    category: 'resources',
    title: 'Treasure God',
    description: 'Earn a total of 50,000,000 gold.',
    type: 'resource',
    resource: 'totalGoldEarned',
    target: 50000000,
    reward: { crystals: 12 },
    icon: '👑',
  },
  {
    id: 'gold_100000000',
    category: 'resources',
    title: 'Midas Touch',
    description: 'Earn a total of 100,000,000 gold.',
    type: 'resource',
    resource: 'totalGoldEarned',
    target: 100000000,
    reward: { crystals: 20 },
    icon: '👑',
  },
  {
    id: 'gold_250000000',
    category: 'resources',
    title: 'Infinite Wealth',
    description: 'Earn a total of 250,000,000 gold.',
    type: 'resource',
    resource: 'totalGoldEarned',
    target: 250000000,
    reward: { crystals: 30 },
    icon: '✨',
  },
  {
    id: 'crystals_5',
    category: 'resources',
    title: 'Crystal Seeker',
    description: 'Earn a total of 5 crystals.',
    type: 'resource',
    resource: 'crystals',
    target: 5,
    reward: { gold: 1000 },
    icon: '🔷',
  },
  {
    id: 'crystals_10',
    category: 'resources',
    title: 'Crystal Collector',
    description: 'Earn a total of 10 crystals.',
    type: 'resource',
    resource: 'crystals',
    target: 10,
    reward: { gold: 2000 },
    icon: '🔷',
  },
  {
    id: 'crystals_25',
    category: 'resources',
    title: 'Crystal Hoarder',
    description: 'Earn a total of 25 crystals.',
    type: 'resource',
    resource: 'crystals',
    target: 25,
    reward: { gold: 5000 },
    icon: '🔷',
  },
  {
    id: 'crystals_50',
    category: 'resources',
    title: 'Crystal Merchant',
    description: 'Earn a total of 50 crystals.',
    type: 'resource',
    resource: 'crystals',
    target: 50,
    reward: { gold: 10000 },
    icon: '💎',
  },
  {
    id: 'crystals_100',
    category: 'resources',
    title: 'Crystal Master',
    description: 'Earn a total of 100 crystals.',
    type: 'resource',
    resource: 'crystals',
    target: 100,
    reward: { gold: 25000 },
    icon: '💎',
  },
  {
    id: 'crystals_250',
    category: 'resources',
    title: 'Crystal Emperor',
    description: 'Earn a total of 250 crystals.',
    type: 'resource',
    resource: 'crystals',
    target: 250,
    reward: { gold: 50000 },
    icon: '💎',
  },
  {
    id: 'crystals_500',
    category: 'resources',
    title: 'Crystal God',
    description: 'Earn a total of 500 crystals.',
    type: 'resource',
    resource: 'crystals',
    target: 500,
    reward: { gold: 100000 },
    icon: '✨',
  }, // Progression quests
  {
    id: 'level_5',
    category: 'progression',
    title: 'Rookie',
    description: 'Reach level 5.',
    type: 'level',
    target: 5,
    reward: { gold: 200, crystals: 1 },
    icon: '🧙',
  },
  {
    id: 'level_10',
    category: 'progression',
    title: 'Novice Adventurer',
    description: 'Reach level 10.',
    type: 'level',
    target: 10,
    reward: { gold: 500, crystals: 1 },
    icon: '🧙',
  },
  {
    id: 'level_25',
    category: 'progression',
    title: 'Experienced Fighter',
    description: 'Reach level 25.',
    type: 'level',
    target: 25,
    reward: { gold: 1000, crystals: 1 },
    icon: '🦸',
  },
  {
    id: 'level_50',
    category: 'progression',
    title: 'Seasoned Hero',
    description: 'Reach level 50.',
    type: 'level',
    target: 50,
    reward: { gold: 2000, crystals: 2 },
    icon: '🦸',
  },
  {
    id: 'level_75',
    category: 'progression',
    title: 'Veteran Warrior',
    description: 'Reach level 75.',
    type: 'level',
    target: 75,
    reward: { gold: 5000, crystals: 2 },
    icon: '🦸',
  },
  {
    id: 'level_100',
    category: 'progression',
    title: 'Elite Champion',
    description: 'Reach level 100.',
    type: 'level',
    target: 100,
    reward: { gold: 10000, crystals: 3 },
    icon: '⭐',
  },
  {
    id: 'level_150',
    category: 'progression',
    title: 'Master Hero',
    description: 'Reach level 150.',
    type: 'level',
    target: 150,
    reward: { gold: 20000, crystals: 5 },
    icon: '⭐',
  },
  {
    id: 'level_200',
    category: 'progression',
    title: 'Legendary Being',
    description: 'Reach level 200.',
    type: 'level',
    target: 200,
    reward: { gold: 40000, crystals: 8 },
    icon: '🌟',
  },
  {
    id: 'level_300',
    category: 'progression',
    title: 'Transcendent',
    description: 'Reach level 300.',
    type: 'level',
    target: 300,
    reward: { gold: 80000, crystals: 12 },
    icon: '🌟',
  },
  {
    id: 'level_500',
    category: 'progression',
    title: 'Ascended One',
    description: 'Reach level 500.',
    type: 'level',
    target: 500,
    reward: { gold: 150000, crystals: 20 },
    icon: '✨',
  },
  {
    id: 'stage_10',
    category: 'progression',
    title: 'First Steps',
    description: 'Reach stage 10.',
    type: 'stage',
    target: 10,
    reward: { gold: 300 },
    icon: '🗺️',
  },
  {
    id: 'stage_25',
    category: 'progression',
    title: 'Wanderer',
    description: 'Reach stage 25.',
    type: 'stage',
    target: 25,
    reward: { gold: 600, crystals: 1 },
    icon: '🗺️',
  },
  {
    id: 'stage_50',
    category: 'progression',
    title: 'Explorer',
    description: 'Reach stage 50.',
    type: 'stage',
    target: 50,
    reward: { gold: 2000, crystals: 1 },
    icon: '🗺️',
  },
  {
    id: 'stage_100',
    category: 'progression',
    title: 'Pathfinder',
    description: 'Reach stage 100.',
    type: 'stage',
    target: 100,
    reward: { gold: 4500, crystals: 1 },
    icon: '🗺️',
  },
  {
    id: 'stage_200',
    category: 'progression',
    title: 'Voyager',
    description: 'Reach stage 200.',
    type: 'stage',
    target: 200,
    reward: { gold: 8000, crystals: 2 },
    icon: '🌍',
  },
  {
    id: 'stage_300',
    category: 'progression',
    title: 'World Traveler',
    description: 'Reach stage 300.',
    type: 'stage',
    target: 300,
    reward: { gold: 10000, crystals: 3 },
    icon: '🌍',
  },
  {
    id: 'stage_500',
    category: 'progression',
    title: 'Dimensional Walker',
    description: 'Reach stage 500.',
    type: 'stage',
    target: 500,
    reward: { gold: 25000, crystals: 5 },
    icon: '🌌',
  },
  {
    id: 'stage_1000',
    category: 'progression',
    title: 'Reality Hopper',
    description: 'Reach stage 1000.',
    type: 'stage',
    target: 1000,
    reward: { gold: 50000, crystals: 10 },
    icon: '🌌',
  },
  {
    id: 'damage_1000',
    category: 'progression',
    title: 'Big Hit',
    description: 'Deal 1,000 damage in a single hit.',
    type: 'damage',
    target: 1000,
    reward: { crystals: 1 },
    icon: '💥',
  },
  {
    id: 'damage_10000',
    category: 'progression',
    title: 'Devastating Strike',
    description: 'Deal 10,000 damage in a single hit.',
    type: 'damage',
    target: 10000,
    reward: { crystals: 2 },
    icon: '💥',
  },
  {
    id: 'damage_100000',
    category: 'progression',
    title: 'Cataclysmic Blow',
    description: 'Deal 100,000 damage in a single hit.',
    type: 'damage',
    target: 100000,
    reward: { crystals: 3 },
    icon: '💢',
  },
  {
    id: 'damage_1000000',
    category: 'progression',
    title: 'Reality Shattering',
    description: 'Deal 1,000,000 damage in a single hit.',
    type: 'damage',
    target: 1000000,
    reward: { crystals: 5 },
    icon: '💢',
  },
  // Item Drop Quests
  {
    id: 'itemdrop_5',
    category: 'drops',
    title: 'First Find',
    description: 'Find 5 items.',
    type: 'item_drop',
    target: 5,
    reward: { item: { rarity: 'rare', type: 'random', tier: 3 } },
    icon: '🎁',
  },
  {
    id: 'itemdrop_25',
    category: 'drops',
    title: 'Treasure Hunter',
    description: 'Find 25 items.',
    type: 'item_drop',
    target: 25,
    reward: { item: { rarity: 'unique', type: 'random', tier: 3 } },
    icon: '🎁',
  },
  {
    id: 'itemdrop_60',
    category: 'drops',
    title: 'Loot Collector',
    description: 'Find 60 items.',
    type: 'item_drop',
    target: 60,
    reward: { item: { rarity: 'unique', type: 'random', tier: 4 } },
    icon: '🎁',
  },
  {
    id: 'itemdrop_150',
    category: 'drops',
    title: 'Relic Seeker',
    description: 'Find 150 items.',
    type: 'item_drop',
    target: 150,
    reward: { item: { rarity: 'legendary', type: 'random', tier: 4 } },
    icon: '🎁',
  },
  {
    id: 'itemdrop_300',
    category: 'drops',
    title: 'Epic Hoarder',
    description: 'Find 300 items.',
    type: 'item_drop',
    target: 300,
    reward: { item: { rarity: 'legendary', type: 'random', tier: 5 } },
    icon: '🎁',
  },
  {
    id: 'itemdrop_750',
    category: 'drops',
    title: 'Mythic Collector',
    description: 'Find 750 items.',
    type: 'item_drop',
    target: 750,
    reward: { item: { rarity: 'mythic', type: 'random', tier: 6 } },
    icon: '🎁',
  },
  // Material Drop Quests
  {
    id: 'matdrop_5',
    category: 'drops',
    title: 'First Material',
    description: 'Collect 5 materials.',
    type: 'material_drop',
    target: 5,
    reward: { item: { rarity: 'rare', type: 'random', tier: 2 } },
    icon: '🪨',
  },
  {
    id: 'matdrop_25',
    category: 'drops',
    title: 'Material Gatherer',
    description: 'Collect 25 materials.',
    type: 'material_drop',
    target: 25,
    reward: { item: { rarity: 'unique', type: 'random', tier: 2 } },
    icon: '🪨',
  },
  {
    id: 'matdrop_60',
    category: 'drops',
    title: 'Resourceful',
    description: 'Collect 60 materials.',
    type: 'material_drop',
    target: 60,
    reward: { item: { rarity: 'unique', type: 'random', tier: 3 } },
    icon: '🪨',
  },
  {
    id: 'matdrop_150',
    category: 'drops',
    title: 'Materialist',
    description: 'Collect 150 materials.',
    type: 'material_drop',
    target: 150,
    reward: { item: { rarity: 'legendary', type: 'random', tier: 4 } },
    icon: '🪨',
  },
  {
    id: 'matdrop_300',
    category: 'drops',
    title: 'Legendary Gatherer',
    description: 'Collect 300 materials.',
    type: 'material_drop',
    target: 300,
    reward: { item: { rarity: 'legendary', type: 'random', tier: 4 } },
    icon: '🪨',
  },
  {
    id: 'matdrop_750',
    category: 'drops',
    title: 'Mythic Prospector',
    description: 'Collect 750 materials.',
    type: 'material_drop',
    target: 750,
    reward: { item: { rarity: 'mythic', type: 'random', tier: 5 } },
    icon: '🪨',
  },
];
